server:
  port: 8080
spring:
  rabbitmq:
    host: dev-mq-1.tae-tea.net,dev-mq-2.tae-tea.net,dev-mq-3.tae-tea.net
    port: 5672
    username: admin
    password: ca&e6I^Z@a!pfh
    listener:
      simple:
        #        每个容器的消费者数量控制，也就是线程池的大小
        concurrency: 2
        max-concurrency: 4
        #        开启失败时重试
        #        retry:
        #          max-attempts: 3
        #          enabled: true
        #       预取的数量,spring amqp2.0开始默认值为250，之前默认为1，最好设置稍微大些
        prefetch: 5
